In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/telco_customer_churn_cleaned.csv")

In [3]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,1936.30
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   str
 1   Gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   str
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   Tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   str
 21  LTV               7043 non-null   float64
dtypes: float64(3), int64(1), str(18)
memory usage: 1.2 MB

In [5]:
df.shape

(7043, 22)

In [6]:
df.isnull().sum()

CustomerID          0
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
LTV                 0
dtype: int64

In [7]:
df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'LTV'],
      dtype='str')

In [8]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [9]:
df.nunique()

CustomerID          7043
Gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
Tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
LTV                 6018
dtype: int64

**1. ANNUAL CHARGES**

In [10]:
df['AnnualCharges']=df['MonthlyCharges']*12

In [11]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV,AnnualCharges
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85,358.2
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.50,No,1936.30,683.4
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70,646.2
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50,507.6
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40,848.4

**2. TENURE GROUP**

In [12]:
df["TenureGroup"] = pd.cut(
    df["Tenure"],
    bins=[-1, 12, 24, 48, 72],
    labels=[
        "0-12 months",
        "13-24 months",
        "25-48 months",
        "49-72 months"
    ]
)

**3. IS MONTH TO MONTH**
( This feature identifies customers who are on month-to-month contracts.Month-to-month customers have a higher churn rate. )

In [13]:
df['IsMonthToMonth']=(df['Contract']=='Month-to-month').astype(int)

In [14]:
df[['IsMonthToMonth','Contract']].head(10)

   IsMonthToMonth        Contract
0               1  Month-to-month
1               0        One year
2               1  Month-to-month
3               0        One year
4               1  Month-to-month
5               1  Month-to-month
6               1  Month-to-month
7               1  Month-to-month
8               1  Month-to-month
9               0        One year

In [15]:
df.to_csv(
    "../data/processed/telco_customer_churn_features.csv",
    index=False
)

In [16]:
pd.crosstab(df["TenureGroup"], df["Churn"], normalize="index").round(3) * 100

Churn           No   Yes
TenureGroup
0-12 months   52.6  47.4
13-24 months  71.3  28.7
25-48 months  79.6  20.4
49-72 months  90.5   9.5

Insight: The longer customers stay, the less likely they are to churn.

In [17]:
pd.crosstab(df["IsMonthToMonth"], df["Churn"], normalize="index").round(3) * 100

Churn             No   Yes
IsMonthToMonth
0               93.2   6.8
1               57.3  42.7

Insight: Month to month customers have more churn rate than other contract type

**4.CREATED SERVICE COUNT COLUMN FOR COUNTING ADDITIONAL SERVICES CHOSEN BY CUSTOMER**

In [18]:
service_columns = [
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies"
]

In [19]:
df["ServiceCount"] = (
    df[service_columns]
    .eq("Yes")
    .sum(axis=1)
)

In [20]:
df["ServiceCount"].value_counts().sort_index()

ServiceCount
0    2219
1     966
2    1033
3    1118
4     852
5     571
6     284
Name: count, dtype: int64

In [21]:
pd.crosstab(
    df["ServiceCount"],
    df["Churn"],
    normalize="index"
).round(3) * 100

Churn           No   Yes
ServiceCount
0             78.6  21.4
1             54.2  45.8
2             64.2  35.8
3             72.6  27.4
4             77.7  22.3
5             87.6  12.4
6             94.7   5.3

Insight: as the service count increases the churn rate decreases

**5. ADDED ELECTRONIC PAYMENT COUNTING COLUMN  (HIGH CHURN RATE FOR ELECTRONIC CHECK)**

In [22]:
df["IsElectronicPayment"] = (df["PaymentMethod"] == "Electronic check").astype(int)

In [23]:
pd.crosstab(
    df['IsElectronicPayment'],
    df['Churn'],
    normalize='index'
).round(3)*100

Churn                  No   Yes
IsElectronicPayment
0                    82.9  17.1
1                    54.7  45.3

Customers using Electronic check have a much higher churn rate than customers using other payment methods.

**6. CREATED HAVE FAMILY OR NOT COLUMN**

In [24]:
df["HasFamily"] = (
    (df["Partner"] == "Yes") |
    (df["Dependents"] == "Yes")
).astype(int)

In [25]:
pd.crosstab(
    df['HasFamily'],
    df['Churn'],
    normalize='index'
).round(3)*100

Churn        No   Yes
HasFamily
0          65.8  34.2
1          80.2  19.8

Insight: customer with no family have high churn rate

In [26]:
df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'LTV',
       'AnnualCharges', 'TenureGroup', 'IsMonthToMonth', 'ServiceCount',
       'IsElectronicPayment', 'HasFamily'],
      dtype='str')

In [27]:
df[[
    "ServiceCount",
    "IsElectronicPayment",
    "IsMonthToMonth",
    "HasFamily"
]].head()

   ServiceCount  IsElectronicPayment  IsMonthToMonth  HasFamily
0             1                    1               1          1
1             2                    0               0          0
2             2                    0               1          0
3             3                    0               0          0
4             0                    1               1          0

In [28]:
#day 3 work

In [29]:
df.columns.tolist()

['CustomerID',
 'Gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'Tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'LTV',
 'AnnualCharges',
 'TenureGroup',
 'IsMonthToMonth',
 'ServiceCount',
 'IsElectronicPayment',
 'HasFamily']

In [30]:
df.shape

(7043, 28)

In [31]:
df.isnull().sum().sum()

np.int64(0)

In [32]:
X = df.drop(columns=["CustomerID", "Churn", "LTV","TenureGroup"])
y = df["Churn"]

In [33]:
X.shape

(7043, 24)

In [34]:
y.shape

(7043,)

In [35]:
X.dtypes

Gender                     str
SeniorCitizen              str
Partner                    str
Dependents                 str
Tenure                   int64
PhoneService               str
MultipleLines              str
InternetService            str
OnlineSecurity             str
OnlineBackup               str
DeviceProtection           str
TechSupport                str
StreamingTV                str
StreamingMovies            str
Contract                   str
PaperlessBilling           str
PaymentMethod              str
MonthlyCharges         float64
TotalCharges           float64
AnnualCharges          float64
IsMonthToMonth           int64
ServiceCount             int64
IsElectronicPayment      int64
HasFamily                int64
dtype: object

**ENCODING CATEGORICAL COLUMN FOR ML**

In [36]:
categorical_cols = X.select_dtypes(include=["object","string"]).columns.tolist()
categorical_cols

['Gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

**CONVERTING THESE TO NUMBERS**

In [37]:
X_encoded=pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)
'''
if the Contract column have 3 values,only 2 columns are created instead of 3(one year and two year).
so if both of them are 0 that means it is month to month
'''

'\nif the Contract column have 3 values,only 2 columns are created instead of 3(one year and two year).\nso if both of them are 0 that means it is month to month\n'

In [38]:
X_encoded.shape

(7043, 35)

In [39]:
X_encoded.head()

,Tenure,MonthlyCharges,TotalCharges,AnnualCharges,IsMonthToMonth,ServiceCount,IsElectronicPayment,HasFamily,Gender_Male,SeniorCitizen_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,29.85,29.85,358.2,1,1,1,1,0,0,...,0,0,0,0,0,0,1,0,1,0
1,34,56.95,1889.50,683.4,0,2,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,2,53.85,108.15,646.2,1,2,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,45,42.30,1840.75,507.6,0,3,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,2,70.70,151.65,848.4,1,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [40]:
X_encoded.dtypes

Tenure                                     int64
MonthlyCharges                           float64
TotalCharges                             float64
AnnualCharges                            float64
IsMonthToMonth                             int64
ServiceCount                               int64
IsElectronicPayment                        int64
HasFamily                                  int64
Gender_Male                                int64
SeniorCitizen_Yes                          int64
Partner_Yes                                int64
Dependents_Yes                             int64
PhoneService_Yes                           int64
MultipleLines_No phone service             int64
MultipleLines_Yes                          int64
InternetService_Fiber optic                int64
InternetService_No                         int64
OnlineSecurity_No internet service         int64
OnlineSecurity_Yes                         int64
OnlineBackup_No internet service           int64
OnlineBackup_Yes                           int64
DeviceProtection_No internet service       int64
DeviceProtection_Yes                       int64
TechSupport_No internet service            int64
TechSupport_Yes                            int64
StreamingTV_No internet service            int64
StreamingTV_Yes                            int64
StreamingMovies_No internet service        int64
StreamingMovies_Yes                        int64
Contract_One year                          int64
Contract_Two year                          int64
PaperlessBilling_Yes                       int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
dtype: object

In [41]:
X_encoded.shape

(7043, 35)

In [42]:
X_encoded.isnull().sum().sum()

np.int64(0)

In [43]:
#checking data types are numeric
X_encoded.dtypes.value_counts()

int64      32
float64     3
Name: count, dtype: int64

**--------------------TRAIN / TEST SPLIT-------------------------**

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,# 20 % for testing
    random_state=42,
    stratify=y #train and test sets keep roughly the same proportion of churn and non-churn customers as the original dataset.
)

In [47]:
X_train.shape

(5634, 35)

In [48]:
X_test.shape

(1409, 35)

In [49]:
y_train.shape

(5634,)

In [50]:
y_test.shape

(1409,)

### Checking Churn Distribution After Train/Test Split

In [51]:
print("Overall churn proportion:")
print(y.value_counts(normalize=True))

print("\nTraining churn proportion:")
print(y_train.value_counts(normalize=True))

print("\nTesting churn proportion:")
print(y_test.value_counts(normalize=True))

Overall churn proportion:
Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

Training churn proportion:
Churn
No     0.734647
Yes    0.265353
Name: proportion, dtype: float64

Testing churn proportion:
Churn
No     0.734564
Yes    0.265436
Name: proportion, dtype: float64

### Feature Scaling 
putting all features on a similar numerical scale so that differences in their original ranges don't unfairly affect the ML model.

In [52]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [53]:
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

X_train_scaled shape: (5634, 35)
X_test_scaled shape: (1409, 35)