# load feature engineered data set

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/telco_customer_churn_features.csv")

In [2]:
df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV,AnnualCharges,ServiceCount
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,29.85,358.2,1
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,One year,No,Mailed check,56.95,1889.50,No,1936.30,683.4,2
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,107.70,646.2,2
3,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1903.50,507.6,3
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,141.40,848.4,0

In [3]:
df.shape

(7043, 24)

In [4]:
df.columns.tolist()

['CustomerID',
 'Gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'Tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'LTV',
 'AnnualCharges',
 'ServiceCount']

In [5]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

# active customer dataset

In [6]:
active_df = df[df["Churn"] == "No"].copy()

active_df = active_df.drop(columns=["LTV"])

In [7]:
active_df.shape

(5174, 23)

In [8]:
active_df.columns.tolist()

['CustomerID',
 'Gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'Tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'AnnualCharges',
 'ServiceCount']

# loading survival analysic data set

In [9]:
customer_ltv = pd.read_csv(
    "../data/processed/customer_ltv_survival.csv"
)

print(customer_ltv["Customer_ID"].head(10).tolist())
print(customer_ltv.shape)

customer_ltv.head()

['9237-HQITU', '7469-LKBCI', '8191-XWSZG', '8779-QRDMV', '1066-JKSGK', '8773-HHUOZ', '7310-EGVHZ', '3413-BMNZE', '6047-YHPVI', '6572-ADKRS']
(7043, 4)

,Customer_ID,Expected_Remaining_Lifetime,MonthlyCharges,Expected_Remaining_LTV
0,9237-HQITU,7.751069,70.70,548.000602
1,7469-LKBCI,55.223945,18.95,1046.493763
2,8191-XWSZG,16.327400,20.65,337.160819
3,8779-QRDMV,27.202775,39.65,1078.590048
4,1066-JKSGK,43.262725,20.15,871.743914

# merge it with customer data

In [10]:
active_df = df[df["Churn"] == "No"].copy()

active_df = active_df.merge(
    customer_ltv[
        [
            "Customer_ID",
            "Expected_Remaining_Lifetime",
            "Expected_Remaining_LTV"
        ]
    ],
    left_on="CustomerID",
    right_on="Customer_ID",
    how="left"
)

active_df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaymentMethod,MonthlyCharges,TotalCharges,Churn,LTV,AnnualCharges,ServiceCount,Customer_ID,Expected_Remaining_Lifetime,Expected_Remaining_LTV
0,7590-VHVEG,Female,No,Yes,No,1,No,No phone service,DSL,No,...,Electronic check,29.85,29.85,No,29.85,358.2,1,7590-VHVEG,32.576010,972.393896
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,Mailed check,56.95,1889.50,No,1936.30,683.4,2,5575-GNVDE,32.746507,1864.913577
2,7795-CFOCW,Male,No,No,No,45,No,No phone service,DSL,Yes,...,Bank transfer (automatic),42.30,1840.75,No,1903.50,507.6,3,7795-CFOCW,25.355202,1072.525028
3,1452-KIOVK,Male,No,No,Yes,22,Yes,Yes,Fiber optic,No,...,Credit card (automatic),89.10,1949.40,No,1960.20,1069.2,2,1452-KIOVK,22.487237,2003.612810
4,6713-OKOMC,Female,No,No,No,10,No,No phone service,DSL,Yes,...,Mailed check,29.75,301.90,No,297.50,357.0,1,6713-OKOMC,26.586060,790.935277

In [11]:
active_df.columns.tolist()

['CustomerID',
 'Gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'Tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'LTV',
 'AnnualCharges',
 'ServiceCount',
 'Customer_ID',
 'Expected_Remaining_Lifetime',
 'Expected_Remaining_LTV']

In [12]:
print("Active customers:", len(active_df))
print(
    "Missing survival predictions:",
    active_df["Expected_Remaining_Lifetime"].isna().sum()
)

Active customers: 5174
Missing survival predictions: 0

# Expected Total LTV

In [13]:
active_df["Expected_Total_LTV"] = (
    active_df["TotalCharges"]
    + active_df["Expected_Remaining_LTV"]
)

active_df[
    [
        "CustomerID",
        "TotalCharges",
        "Expected_Remaining_LTV",
        "Expected_Total_LTV"
    ]
].head(10)

   CustomerID  TotalCharges  Expected_Remaining_LTV  Expected_Total_LTV
0  7590-VHVEG         29.85              972.393896         1002.243896
1  5575-GNVDE       1889.50             1864.913577         3754.413577
2  7795-CFOCW       1840.75             1072.525028         2913.275028
3  1452-KIOVK       1949.40             2003.612810         3953.012810
4  6713-OKOMC        301.90              790.935277         1092.835277
5  6388-TABGU       3487.95              430.441003         3918.391003
6  9763-GRSKD        587.45             1372.715061         1960.165061
7  7469-LKBCI        326.80             1046.493763         1373.293763
8  8091-TTVAX       5681.10             1121.531005         6802.631005
9  5129-JLPIS       2686.05             2423.837011         5109.887011

# defining X and y

In [14]:
X = active_df.drop(
    columns=[
        "CustomerID",
        "Customer_ID",
        "Churn",
        "TotalCharges",
        "Expected_Remaining_Lifetime",
        "Expected_Remaining_LTV",
        "Expected_Total_LTV",
        "AnnualCharges",
        "LTV",
        "Predicted_LTV",
        "Predicted_Total_LTV"
    ],
    errors="ignore"
)

y = active_df["Expected_Remaining_LTV"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

X shape: (5174, 19)
y shape: (5174,)

Features:
['Gender', 'SeniorCitizen', 'Partner', 'Dependents', 'Tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'ServiceCount']

Target:
Expected_Remaining_LTV

##  Train-Test Split

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [16]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4139, 19), (1035, 19), (4139,), (1035,))

## Identify Categorical and Numerical Features

In [17]:
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

categorical_cols, numeric_cols

(['Gender',
  'SeniorCitizen',
  'Partner',
  'Dependents',
  'PhoneService',
  'MultipleLines',
  'InternetService',
  'OnlineSecurity',
  'OnlineBackup',
  'DeviceProtection',
  'TechSupport',
  'StreamingTV',
  'StreamingMovies',
  'Contract',
  'PaperlessBilling',
  'PaymentMethod'],
 ['Tenure', 'MonthlyCharges', 'ServiceCount'])

##   Preprocessing Pipeline

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

##  Build the Linear Regression Pipeline

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

linear_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

##  Train the Linear Regression Model

In [20]:
linear_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod']),
                                                 ('num', 'passthrough',
                                                  ['Tenure', 'MonthlyCharges',
                                                   'ServiceCount'])])),
                ('model', LinearRegression())])

##  Generate LTV Predictions

In [21]:
y_pred_linear = linear_model.predict(X_test)

In [22]:
y_pred_linear[:10]

array([1245.54108858, -780.76101624, 1358.47572545,   -5.03493668,
       1096.39242751, 1187.89216547,   83.8856949 , 1578.15715725,
       1179.6903961 , 2582.09441936])

##  Evaluate Linear Regression

The model is evaluated on the unseen test set using three regression metrics:

- **MAE (Mean Absolute Error):** Measures the average absolute difference between actual and predicted lifetime revenue.
- **RMSE (Root Mean Squared Error):** Measures prediction error while giving greater weight to larger errors.
- **R² (R-squared):** Measures how much of the variation in lifetime revenue is explained by the model.

Lower MAE and RMSE indicate better performance, while a higher R² indicates better performance.

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_linear = mean_absolute_error(y_test, y_pred_linear)
rmse_linear = np.sqrt(mean_squared_error(y_test, y_pred_linear))
r2_linear = r2_score(y_test, y_pred_linear)

print("Linear Regression")
print("MAE :", mae_linear)
print("RMSE:", rmse_linear)
print("R²  :", r2_linear)

Linear Regression
MAE : 428.6239915070517
RMSE: 545.7310625649649
R²  : 0.677328867881743

##  Random Forest Regression

In [24]:
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

In [25]:
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod']),
                                                 ('num', 'passthrough',
                                                  ['Tenure', 'MonthlyCharges',
                                                   'ServiceCount'])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

##  Generate Random Forest Predictions

In [26]:
y_pred_rf = rf_model.predict(X_test)

In [27]:
y_pred_rf[:10]

array([ 831.24309996,    0.        ,  579.90470892,  460.74526257,
        422.52334188,  887.73068141,  477.687796  , 1342.36528932,
        895.04683715, 3984.25854525])

##  Evaluate Random Forest Regression

In [28]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Regression")
print("MAE :", mae_rf)
print("RMSE:", rmse_rf)
print("R²  :", r2_rf)

Random Forest Regression
MAE : 97.13028809976714
RMSE: 177.7409517759212
R²  : 0.9657722960186332

In [29]:
import xgboost
print(xgboost.__version__)

3.4.0

##  XGBoost Regression

In [30]:
from xgboost import XGBRegressor

xgb_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", XGBRegressor(
            n_estimators=200,
            learning_rate=0.05,
            max_depth=3,
            random_state=42,
            objective="reg:squarederror"
        ))
    ]
)

In [31]:
xgb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'SeniorCitizen',
                                                   'Partner', 'Dependents',
                                                   'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=3, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=None,
                              num_parallel_tree=None, ...))])

##  Generate XGBoost Predictions

In [32]:
y_pred_xgb = xgb_model.predict(X_test)
y_pred_xgb[:10]

array([ 825.9881  ,  -41.739014,  620.27966 ,  524.44037 ,  713.80566 ,
        871.11316 ,  388.71927 , 1249.2947  ,  871.11316 , 3739.7751  ],
      dtype=float32)

##  Evaluate XGBoost Regression

In [33]:
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2_xgb = r2_score(y_test, y_pred_xgb)

print("XGBoost Regression")
print("MAE :", mae_xgb)
print("RMSE:", rmse_xgb)
print("R²  :", r2_xgb)

XGBoost Regression
MAE : 137.48352670317976
RMSE: 215.01760000682128
R²  : 0.9499100285054496

##  Compare Regression Models

In [34]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "XGBoost"
    ],
    "MAE": [
        mae_linear,
        mae_rf,
        mae_xgb
    ],
    "RMSE": [
        rmse_linear,
        rmse_rf,
        rmse_xgb
    ],
    "R2": [
        r2_linear,
        r2_rf,
        r2_xgb
    ]
})

results

               Model         MAE        RMSE        R2
0  Linear Regression  428.623992  545.731063  0.677329
1      Random Forest   97.130288  177.740952  0.965772
2            XGBoost  137.483527  215.017600  0.949910

##  XGBoost Hyperparameter Tuning

In [35]:
from sklearn.model_selection import RandomizedSearchCV

In [36]:
param_grid = {
    "model__n_estimators": [100, 200, 300, 500],
    "model__learning_rate": [0.01, 0.03, 0.05, 0.1],
    "model__max_depth": [2, 3, 4, 5],
    "model__subsample": [0.7, 0.8, 0.9, 1.0],
    "model__colsample_bytree": [0.7, 0.8, 0.9, 1.0]
}

In [37]:
xgb_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_grid,
    n_iter=20,
    scoring="neg_mean_absolute_error",
    cv=3,
    random_state=42,
    n_jobs=1
)

In [38]:
xgb_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('cat',
                                                                               OneHotEncoder(handle_unknown='ignore'),
                                                                               ['Gender',
                                                                                'SeniorCitizen',
                                                                                'Partner',
                                                                                'Dependents',
                                                                                'PhoneService',
                                                                                'MultipleLines',
                                                                                'InternetService',
                                                                                'OnlineSecurity',
                                                                                'OnlineBackup',
                                                                                'DeviceProtection',
                                                                                'TechSupport',
                                                                                'StreamingTV',
                                                                                'StreamingMovies',
                                                                                'Contract',...
                                                           multi_strategy=None,
                                                           n_estimators=200,
                                                           n_jobs=None,
                                                           num_parallel_tree=None, ...))]),
                   n_iter=20, n_jobs=1,
                   param_distributions={'model__colsample_bytree': [0.7, 0.8,
                                                                    0.9, 1.0],
                                        'model__learning_rate': [0.01, 0.03,
                                                                 0.05, 0.1],
                                        'model__max_depth': [2, 3, 4, 5],
                                        'model__n_estimators': [100, 200, 300,
                                                                500],
                                        'model__subsample': [0.7, 0.8, 0.9,
                                                             1.0]},
                   random_state=42, scoring='neg_mean_absolute_error')

In [39]:
xgb_search.best_params_

{'model__subsample': 0.8,
 'model__n_estimators': 500,
 'model__max_depth': 4,
 'model__learning_rate': 0.1,
 'model__colsample_bytree': 0.9}

In [40]:
xgb_search.best_score_

np.float64(-63.85075983439483)

## Evaluate Tuned XGBoost Model

In [41]:
best_xgb = xgb_search.best_estimator_

y_pred_tuned = best_xgb.predict(X_test)

In [42]:
mae_tuned = mean_absolute_error(y_test, y_pred_tuned)
rmse_tuned = np.sqrt(mean_squared_error(y_test, y_pred_tuned))
r2_tuned = r2_score(y_test, y_pred_tuned)

print("Tuned XGBoost Regression")
print("MAE :", mae_tuned)
print("RMSE:", rmse_tuned)
print("R²  :", r2_tuned)

Tuned XGBoost Regression
MAE : 60.48003983730632
RMSE: 95.87085839816099
R²  : 0.9900419111627028

## Generate Final LTV Predictions

In [43]:
active_df["Predicted_Remaining_LTV_Raw"] = best_xgb.predict(X)

active_df["Predicted_Remaining_LTV"] = (
    active_df["Predicted_Remaining_LTV_Raw"].clip(lower=0)
)

active_df["Predicted_Total_LTV"] = (
    active_df["TotalCharges"]
    + active_df["Predicted_Remaining_LTV"]
)

In [44]:
final_ltv_output = active_df[
    [
        "CustomerID",
        "TotalCharges",
        "Predicted_Remaining_LTV",
        "Predicted_Total_LTV"
    ]
].copy()

final_ltv_output.head(20)

    CustomerID  TotalCharges  Predicted_Remaining_LTV  Predicted_Total_LTV
0   7590-VHVEG         29.85              1020.397339          1050.247339
1   5575-GNVDE       1889.50              1885.079102          3774.579102
2   7795-CFOCW       1840.75              1042.676392          2883.426392
3   1452-KIOVK       1949.40              2025.033813          3974.433813
4   6713-OKOMC        301.90               780.053040          1081.953040
5   6388-TABGU       3487.95               392.858368          3880.808368
6   9763-GRSKD        587.45              1412.248291          1999.698291
7   7469-LKBCI        326.80              1060.407104          1387.207104
8   8091-TTVAX       5681.10              1070.385986          6751.485986
9   5129-JLPIS       2686.05              2382.538574          5068.588574
10  3655-SNQYZ       7895.15               327.802002          8222.952002
11  8191-XWSZG       1022.95               338.350830          1361.300830
12  9959-WOFKT       7382.25               174.703140          7556.953140
13  4183-MYFRB       1862.90              1295.065918          3157.965918
14  1680-VDCWW        202.25              1157.934204          1360.184204
15  3638-WEABW       3505.10               768.372437          4273.472437
16  6322-HRPFA       2970.30               967.907471          3938.207471
17  6865-JZNKO       1530.60              1213.431519          2744.031519
18  5248-YGIJN       6369.45                 0.000000          6369.450000
19  3841-NFECX       6766.95                81.044113          6847.994113

In [45]:
final_ltv_output.to_csv(
    "../data/processed/customer_ltv_predictions.csv",
    index=False
)

print("LTV predictions saved successfully.")

LTV predictions saved successfully.

## Feature Importance

In [46]:
import pandas as pd

# Get transformed feature names from the preprocessing pipeline
feature_names = best_xgb.named_steps["preprocessor"].get_feature_names_out()

# Get feature importance from XGBoost
importance = best_xgb.named_steps["model"].feature_importances_

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
}).sort_values(
    "Importance",
    ascending=False
)

feature_importance.head(15)

                                       Feature  Importance
45                           num__ServiceCount    0.223925
15                     cat__InternetService_No    0.134717
43                                 num__Tenure    0.095611
34                cat__Contract_Month-to-month    0.074494
18                     cat__OnlineSecurity_Yes    0.053286
36                      cat__Contract_Two year    0.036701
12                      cat__MultipleLines_Yes    0.035361
14            cat__InternetService_Fiber optic    0.030613
21                       cat__OnlineBackup_Yes    0.025424
5                             cat__Partner_Yes    0.023934
41         cat__PaymentMethod_Electronic check    0.023168
44                         num__MonthlyCharges    0.020177
40  cat__PaymentMethod_Credit card (automatic)    0.019787
35                      cat__Contract_One year    0.018822
13                    cat__InternetService_DSL    0.018572

## Prediction Sanity Check

In [47]:
# Final LTV sanity check

print("Predicted Remaining LTV:")
print(active_df["Predicted_Remaining_LTV"].describe())

print("\nPredicted Total LTV:")
print(active_df["Predicted_Total_LTV"].describe())

print("\nNegative Remaining LTV:",
      (active_df["Predicted_Remaining_LTV"] < 0).sum())

print("Negative Total LTV:",
      (active_df["Predicted_Total_LTV"] < 0).sum())

Predicted Remaining LTV:
count    5174.000000
mean     1062.412964
std       921.104553
min         0.000000
25%       380.766197
50%       859.555634
75%      1470.012695
max      5787.926758
Name: Predicted_Remaining_LTV, dtype: float64

Predicted Total LTV:
count    5174.000000
mean     3612.324368
std      2232.655842
min       362.012610
25%      1468.200267
50%      3192.952930
75%      5455.499295
max      8690.212024
Name: Predicted_Total_LTV, dtype: float64

Negative Remaining LTV: 0
Negative Total LTV: 0

## Save Final LTV Model

In [48]:
import joblib

joblib.dump(
    best_xgb,
    "../models/ltv_xgboost_model.pkl"
)

print("Final LTV model saved successfully.")

Final LTV model saved successfully.